#!/bin/bash

set -e

POSTGRES="psql --username ${POSTGRES_USER} --dbname ${POSTGRES_DB}"

echo "Creating database role: ${HOMEBOX_USER}"
$POSTGRES <<-END_OF_SQL
CREATE USER "${HOMEBOX_USER}" WITH PASSWORD '${HOMEBOX_PASSWORD}';
END_OF_SQL

echo "Creating database: ${HOMEBOX_DB}"
$POSTGRES <<-END_OF_SQL
CREATE DATABASE "${HOMEBOX_DB}" WITH OWNER "${HOMEBOX_USER}" ENCODING 'UTF8' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE "${HOMEBOX_DB}" TO "${HOMEBOX_USER}";
END_OF_SQL
