networks:
  common:
    driver: bridge
services:

  #####################################################################################################################
  # OpenSearch
  #####################################################################################################################
  opensearch:
    # Use the command below to list available versions:
    # curl -s "https://registry.hub.docker.com/v2/repositories/opensearchproject/opensearch/tags/?page_size=100" | jq -r '.results[].name' | sort -r
    image: opensearchproject/opensearch:3.2.0
    container_name: home-ecosystem-opensearch
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${HOME_ECOSYSTEM_OPENSEARCH_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/opensearch/data:/usr/share/opensearch/data:rw
    networks:
      - common
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: unless-stopped

  #####################################################################################################################
  # FluentBit
  #####################################################################################################################
  fluentbit:
    # Use the command below to list available versions:
    # curl -s "https://registry.hub.docker.com/v2/repositories/fluent/fluent-bit/tags/?page_size=100" | jq -r '.results[].name' | sort -r
    image: fluent/fluent-bit:4.0.9
    container_name: home-ecosystem-fluentbit
    depends_on:
      - opensearch
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - OPENSEARCH_PASSWORD=${HOME_ECOSYSTEM_OPENSEARCH_ADMIN_PASSWORD}
    volumes:
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/fluentbit/scripts:/fluent-bit/etc/scripts:ro
    networks:
      - common
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    restart: unless-stopped

  #####################################################################################################################
  # OpenSearch Dashboards
  #####################################################################################################################
  opensearch-dashboards:
    # Use the command below to list available versions:
    # curl -s "https://registry.hub.docker.com/v2/repositories/opensearchproject/opensearch-dashboards/tags/?page_size=100" | jq -r '.results[].name' | sort -r
    image: opensearchproject/opensearch-dashboards:3.2.0
    container_name: home-ecosystem-opensearch-dashboards
    depends_on:
      - fluentbit
      - opensearch
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - OPENSEARCH_HOSTS=https://home-ecosystem-opensearch:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${HOME_ECOSYSTEM_OPENSEARCH_ADMIN_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - common
    restart: unless-stopped

  #####################################################################################################################
  # PostgreSQL database
  #####################################################################################################################
  postgres:
    # Use the command below to list available versions:
    # curl -s "https://registry.hub.docker.com/v2/repositories/library/postgres/tags/?page_size=100" | jq -r '.results[].name' |  sort -r
    image: postgres:17.6
    container_name: home-ecosystem-postgres
    depends_on:
      - fluentbit
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - POSTGRES_DB=${HOME_ECOSYSTEM_POSTGRES_DB:-postgres}
      - POSTGRES_USER=${HOME_ECOSYSTEM_POSTGRES_USERNAME:-home_ecosystem}
      - POSTGRES_PASSWORD=${HOME_ECOSYSTEM_POSTGRES_PASSWORD:-CHANGE ME!!!}
      - HOMEBOX_DB=${HOME_ECOSYSTEM_HOMEBOX_DB:-homebox}
      - HOMEBOX_USER=${HOME_ECOSYSTEM_HOMEBOX_DB_USERNAME:-homebox}
      - HOMEBOX_PASSWORD=${HOME_ECOSYSTEM_HOMEBOX_DB_PASSWORD:-CHANGE ME!!!}
    ports:
      - "5432:5432/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/postgres/data:/var/lib/postgresql/data:rw
      - ${HOME_ECOSYSTEM_TMP_DIR:-.tmp}/postgres-init:/docker-entrypoint-initdb.d:rw
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/homebox/postgres-init/homebox.sh:/docker-entrypoint-initdb.d/homebox.sh
    networks:
      - common
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: home-ecosystem-postgres
    restart: unless-stopped

  #####################################################################################################################
  # Homebox
  #####################################################################################################################
  homebox:
    # Use the command below to list available versions:
    # curl -s "https://registry.hub.docker.com/v2/repositories/sysadminsmedia/homebox/tags/?page_size=100" | jq -r '.results[].name' | sort -r
    image: sysadminsmedia/homebox:0.21.0
    container_name: home-ecosystem-homebox
    depends_on:
      - postgres
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_FILE_UPLOAD=10
      - HBOX_OPTIONS_ALLOW_ANALYTICS=${HOME_ECOSYSTEM_HOMEBOX_ALLOW_ANALYTICS:-false}
      - HBOX_DATABASE_DRIVER=postgres
      - HBOX_DATABASE_HOST=home-ecosystem-postgres
      - HBOX_DATABASE_PORT=5432
      - HBOX_DATABASE_DATABASE=${HOME_ECOSYSTEM_HOMEBOX_DB:-homebox}
      - HBOX_DATABASE_USERNAME=${HOME_ECOSYSTEM_HOMEBOX_DB_USERNAME:-homebox}
      - HBOX_DATABASE_PASSWORD=${HOME_ECOSYSTEM_HOMEBOX_DB_PASSWORD:-CHANGE ME!!!}
      - HBOX_DATABASE_SSL_MODE=disable
    ports:
      - "7745:7745/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/homebox/data:/data:rw
    networks:
      - common
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: home-ecosystem-homebox
    restart: unless-stopped

  #####################################################################################################################
  # Plex Media Server
  #####################################################################################################################
  plex:
    # Use the command below to list available versions:
    # curl -s "https://registry.hub.docker.com/v2/repositories/linuxserver/plex/tags/?page_size=100" | jq -r '.results[].name' | sort -r
    image: linuxserver/plex:1.41.9
    container_name: home-ecosystem-plex
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${HOME_ECOSYSTEM_PLEX_CLAIM:-}
    volumes:
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/plex/config:/config:rw
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/plex/transcode:/transcode:rw
      - ${HOME_ECOSYSTEM_PLEX_MEDIA_DIR:-.var/plex/media}:/external-media:ro
    networks:
      - common
    ports:
      - "32400:32400/tcp" # web UI
      - "3005:3005/tcp"   # plex companion
      - "8324:8324/tcp"   # roku discovery
      - "32469:32469/tcp" # DLNA
      - "1900:1900/udp"   # DLNA discovery
      - "32410:32410/udp" # GDM network discovery
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: home-ecosystem-plex
    restart: unless-stopped

  #####################################################################################################################
  # Nginx reverse proxy
  #####################################################################################################################
  nginx:
    # Use the command below to list available versions:
    # curl -s "https://registry.hub.docker.com/v2/repositories/library/nginx/tags/?page_size=100" | jq -r '.results[].name' | sort -r
    image: nginx:1.29.1
    container_name: home-ecosystem-nginx
    depends_on:
      - homebox
      - plex
      - opensearch-dashboards
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
    volumes:
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/homebox/nginx/homebox.conf:/etc/nginx/conf.d/homebox.conf:ro
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/homebox/nginx/customization:/usr/share/nginx/homebox-customization:ro
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/plex/nginx/plex.conf:/etc/nginx/conf.d/plex.conf:ro
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/opensearch/nginx/opensearch.conf:/etc/nginx/conf.d/opensearch.conf:ro
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/nginx/logs:/var/log/nginx:rw
    networks:
      - common
    ports:
      - "80:80/tcp"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: home-ecosystem-nginx
    restart: unless-stopped
