networks:
  common:
    driver: bridge
services:

  #####################################################################################################################
  # PostgreSQL database
  #####################################################################################################################
  postgres:
    image: postgres:15
    container_name: home-ecosystem-postgres
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - POSTGRES_DB=${HOME_ECOSYSTEM_POSTGRES_DB:-postgres}
      - POSTGRES_USER=${HOME_ECOSYSTEM_POSTGRES_USERNAME:-home_ecosystem}
      - POSTGRES_PASSWORD=${HOME_ECOSYSTEM_POSTGRES_PASSWORD:-CHANGE ME!!!}
      - HOMEBOX_DB=${HOME_ECOSYSTEM_HOMEBOX_DB:-homebox}
      - HOMEBOX_USER=${HOME_ECOSYSTEM_HOMEBOX_DB_USERNAME:-homebox}
      - HOMEBOX_PASSWORD=${HOME_ECOSYSTEM_HOMEBOX_DB_PASSWORD:-CHANGE ME!!!}
    ports:
      - "5432:5432/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/postgres/data:/var/lib/postgresql/data:rw
      - ${HOME_ECOSYSTEM_TMP_DIR:-.tmp}/postgres-init:/docker-entrypoint-initdb.d:rw
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/homebox/postgres-init/homebox.sh:/docker-entrypoint-initdb.d/homebox.sh
    networks:
      - common
    restart: unless-stopped

  #####################################################################################################################
  # Homebox
  #####################################################################################################################
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:main
    container_name: home-ecosystem-homebox
    depends_on:
      - postgres
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_FILE_UPLOAD=10
      - HBOX_OPTIONS_ALLOW_ANALYTICS=${HOME_ECOSYSTEM_HOMEBOX_ALLOW_ANALYTICS:-false}
      - HBOX_DATABASE_DRIVER=postgres
      - HBOX_DATABASE_HOST=home-ecosystem-postgres
      - HBOX_DATABASE_PORT=5432
      - HBOX_DATABASE_DATABASE=${HOME_ECOSYSTEM_HOMEBOX_DB:-homebox}
      - HBOX_DATABASE_USERNAME=${HOME_ECOSYSTEM_HOMEBOX_DB_USERNAME:-homebox}
      - HBOX_DATABASE_PASSWORD=${HOME_ECOSYSTEM_HOMEBOX_DB_PASSWORD:-CHANGE ME!!!}
      - HBOX_DATABASE_SSL_MODE=disable
    ports:
      - "7745:7745/tcp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/homebox/data:/var/lib/homebox:rw
    networks:
      - common
    restart: unless-stopped

  #####################################################################################################################
  # Plex Media Server
  #####################################################################################################################
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: home-ecosystem-plex
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${HOME_ECOSYSTEM_PLEX_CLAIM:-}
    volumes:
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/plex/config:/config:rw
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/plex/transcode:/transcode:rw
      - ${HOME_ECOSYSTEM_PLEX_MEDIA_DIR:-.var/plex/media}:/external-media:ro
    networks:
      - common
    ports:
      - "32400:32400/tcp" # web UI
      - "3005:3005/tcp"   # plex companion
      - "8324:8324/tcp"   # roku discovery
      - "32469:32469/tcp" # DLNA
      - "1900:1900/udp"   # DLNA discovery
      - "32410:32410/udp" # GDM network discovery
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    restart: unless-stopped


  #####################################################################################################################
  # OpenSearch
  #####################################################################################################################
  opensearch:
    image: opensearchproject/opensearch:2.14.0
    container_name: home-ecosystem-opensearch
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${HOME_ECOSYSTEM_OPENSEARCH_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/opensearch/data:/usr/share/opensearch/data:rw
    networks:
      - common
    ports:
      - "9200:9200"
      - "9600:9600"
    restart: unless-stopped


  #####################################################################################################################
  # OpenSearch Dashboards
  #####################################################################################################################
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.14.0
    container_name: home-ecosystem-opensearch-dashboards
    depends_on:
      - opensearch
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
      - OPENSEARCH_HOSTS=https://home-ecosystem-opensearch:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=${HOME_ECOSYSTEM_OPENSEARCH_ADMIN_PASSWORD}
    ports:
      - "5601:5601"
    networks:
      - common
    restart: unless-stopped

  #####################################################################################################################
  # Nginx reverse proxy
  #####################################################################################################################
  nginx:
    image: nginx:latest
    container_name: home-ecosystem-nginx
    depends_on:
      - homebox
      - plex
      - opensearch-dashboards
    environment:
      - TZ=${HOME_ECOSYSTEM_TIMEZONE:-UTC}
    volumes:
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/homebox/nginx/homebox.conf:/etc/nginx/conf.d/homebox.conf:ro
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/plex/nginx/plex.conf:/etc/nginx/conf.d/plex.conf:ro
      - ${HOME_ECOSYSTEM_PROJECT_DIR:-.}/apps/opensearch/nginx/opensearch.conf:/etc/nginx/conf.d/opensearch.conf:ro
      - ${HOME_ECOSYSTEM_VAR_DIR:-.var}/nginx/logs:/var/log/nginx:rw
    networks:
      - common
    ports:
      - "80:80/tcp"
    restart: unless-stopped
